export const All_ADDEXTRA_REQUEST = "All_ADDEXTRA_REQUEST";
export const All_ADDEXTRA_SUCCESS = "All_ADDEXTRA_SUCCESS";
export const All_ADDEXTRA_FAIL = "All_ADDEXTRA_FAIL";

export const NEW_ADDEXTRA_REQUEST = "NEW_ADDEXTRA_REQUEST";
export const NEW_ADDEXTRA_SUCCESS = "NEW_ADDEXTRA_SUCCESS";
export const NEW_ADDEXTRA_RESET = "NEW_ADDEXTRA_RESET";
export const NEW_ADDEXTRA_FAIL = "NEW_ADDEXTRA_FAIL";

export const UPDATE_ADDEXTRA_REQUEST = "UPDATE_ADDEXTRA_REQUEST";
export const UPDATE_ADDEXTRA_SUCCESS = "UPDATE_ADDEXTRA_SUCCESS";
export const UPDATE_ADDEXTRA_RESET = "UPDATE_ADDEXTRA_RESET";
export const UPDATE_ADDEXTRA_FAIL = "UPDATE_ADDEXTRA_FAIL";

export const DELETE_ADDEXTRA_REQUEST = "DELETE_ADDEXTRA_REQUEST";
export const DELETE_ADDEXTRA_SUCCESS = "DELETE_ADDEXTRA_SUCCESS";
export const DELETE_ADDEXTRA_RESET = "DELETE_ADDEXTRA_RESET";
export const DELETE_ADDEXTRA_FAIL = "DELETE_ADDEXTRA_FAIL";

export const SINGLE_ADDEXTRA_REQUEST = "SINGLE_ADDEXTRA_REQUEST";
export const SINGLE_ADDEXTRA_SUCCESS = "SINGLE_ADDEXTRA_SUCCESS";
export const SINGLE_ADDEXTRA_FAIL = "SINGLE_ADDEXTRA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";