export const All_ADDON_REQUEST = "All_ADDON_REQUEST";
export const All_ADDON_SUCCESS = "All_ADDON_SUCCESS";
export const All_ADDON_FAIL = "All_ADDON_FAIL";

export const NEW_ADDON_REQUEST = "NEW_ADDON_REQUEST";
export const NEW_ADDON_SUCCESS = "NEW_ADDON_SUCCESS";
export const NEW_ADDON_RESET = "NEW_ADDON_RESET";
export const NEW_ADDON_FAIL = "NEW_ADDON_FAIL";

export const UPDATE_ADDON_REQUEST = "UPDATE_ADDON_REQUEST";
export const UPDATE_ADDON_SUCCESS = "UPDATE_ADDON_SUCCESS";
export const UPDATE_ADDON_RESET = "UPDATE_ADDON_RESET";
export const UPDATE_ADDON_FAIL = "UPDATE_ADDON_FAIL";

export const DELETE_ADDON_REQUEST = "DELETE_ADDON_REQUEST";
export const DELETE_ADDON_SUCCESS = "DELETE_ADDON_SUCCESS";
export const DELETE_ADDON_RESET = "DELETE_ADDON_RESET";
export const DELETE_ADDON_FAIL = "DELETE_ADDON_FAIL";

export const SINGLE_ADDON_REQUEST = "SINGLE_ADDON_REQUEST";
export const SINGLE_ADDON_SUCCESS = "SINGLE_ADDON_SUCCESS";
export const SINGLE_ADDON_FAIL = "SINGLE_ADDON_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";