export const All_BANNER_REQUEST = "All_BANNER_REQUEST";
export const All_BANNER_SUCCESS = "All_BANNER_SUCCESS";
export const All_BANNER_FAIL = "All_BANNER_FAIL";

export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_RESET = "DELETE_BANNER_RESET";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";