export const All_COUPONCODE_REQUEST = "All_COUPONCODE_REQUEST";
export const All_COUPONCODE_SUCCESS = "All_COUPONCODE_SUCCESS";
export const All_COUPONCODE_FAIL = "All_COUPONCODE_FAIL";

export const NEW_COUPONCODE_REQUEST = "NEW_COUPONCODE_REQUEST";
export const NEW_COUPONCODE_SUCCESS = "NEW_COUPONCODE_SUCCESS";
export const NEW_COUPONCODE_RESET = "NEW_COUPONCODE_RESET";
export const NEW_COUPONCODE_FAIL = "NEW_COUPONCODE_FAIL";

export const UPDATE_COUPONCODE_REQUEST = "UPDATE_COUPONCODE_REQUEST";
export const UPDATE_COUPONCODE_SUCCESS = "UPDATE_COUPONCODE_SUCCESS";
export const UPDATE_COUPONCODE_RESET = "UPDATE_COUPONCODE_RESET";
export const UPDATE_COUPONCODE_FAIL = "UPDATE_COUPONCODE_FAIL";

export const DELETE_COUPONCODE_REQUEST = "DELETE_COUPONCODE_REQUEST";
export const DELETE_COUPONCODE_SUCCESS = "DELETE_COUPONCODE_SUCCESS";
export const DELETE_COUPONCODE_RESET = "DELETE_COUPONCODE_RESET";
export const DELETE_COUPONCODE_FAIL = "DELETE_COUPONCODE_FAIL";

export const SINGLE_COUPONCODE_REQUEST = "SINGLE_COUPONCODE_REQUEST";
export const SINGLE_COUPONCODE_SUCCESS = "SINGLE_COUPONCODE_SUCCESS";
export const SINGLE_COUPONCODE_FAIL = "SINGLE_COUPONCODE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";