export const All_GETTOUCH_REQUEST = "All_GETTOUCH_REQUEST";
export const All_GETTOUCH_SUCCESS = "All_GETTOUCH_SUCCESS";
export const All_GETTOUCH_FAIL = "All_GETTOUCH_FAIL";

export const NEW_GETTOUCH_REQUEST = "NEW_GETTOUCH_REQUEST";
export const NEW_GETTOUCH_SUCCESS = "NEW_GETTOUCH_SUCCESS";
export const NEW_GETTOUCH_FAIL = "NEW_GETTOUCH_FAIL";
export const NEW_GETTOUCH_RESET = "NEW_GETTOUCH_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";