export const All_RESTAURANT_REQUEST = "All_RESTAURANT_REQUEST";
export const All_RESTAURANT_SUCCESS = "All_RESTAURANT_SUCCESS";
export const All_RESTAURANT_FAIL = "All_RESTAURANT_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";

export const SINGLE_RESTAURANT_REQUEST = "RESET_PASSWORD_REQUEST";
export const SINGLE_RESTAURANT_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const SINGLE_RESTAURANT_FAIL = "RESET_PASSWORD_FAIL";

export const UPDATE_SINGLE_RESTAURANT_REQUEST = "UPDATE_RESET_PASSWORD_REQUEST";
export const UPDATE_SINGLE_RESTAURANT_SUCCESS = "UPDATE_RESET_PASSWORD_SUCCESS";
export const UPDATE_SINGLE_RESTAURANT_FAIL = "UPDATE_RESET_PASSWORD_FAIL";
export const UPDATE_SINGLE_RESTAURANT_RESET = "UPDATE_RESET_PASSWORD_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";