export const All_SETTING_REQUEST = "All_SETTING_REQUEST";
export const All_SETTING_SUCCESS = "All_SETTING_SUCCESS";
export const All_SETTING_FAIL = "All_SETTING_FAIL";

export const UPDATE_SETTING_REQUEST = "UPDATE_SETTING_REQUEST";
export const UPDATE_SETTING_SUCCESS = "UPDATE_SETTING_SUCCESS";
export const UPDATE_SETTING_RESET = "UPDATE_SETTING_RESET";
export const UPDATE_SETTING_FAIL = "UPDATE_SETTING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";