export const All_VARIANT_REQUEST = "All_VARIANT_REQUEST";
export const All_VARIANT_SUCCESS = "All_VARIANT_SUCCESS";
export const All_VARIANT_FAIL = "All_VARIANT_FAIL";

export const NEW_VARIANT_REQUEST = "NEW_VARIANT_REQUEST";
export const NEW_VARIANT_SUCCESS = "NEW_VARIANT_SUCCESS";
export const NEW_VARIANT_RESET = "NEW_VARIANT_RESET";
export const NEW_VARIANT_FAIL = "NEW_VARIANT_FAIL";

export const UPDATE_VARIANT_REQUEST = "UPDATE_VARIANT_REQUEST";
export const UPDATE_VARIANT_SUCCESS = "UPDATE_VARIANT_SUCCESS";
export const UPDATE_VARIANT_RESET = "UPDATE_VARIANT_RESET";
export const UPDATE_VARIANT_FAIL = "UPDATE_VARIANT_FAIL";

export const DELETE_VARIANT_REQUEST = "DELETE_VARIANT_REQUEST";
export const DELETE_VARIANT_SUCCESS = "DELETE_VARIANT_SUCCESS";
export const DELETE_VARIANT_RESET = "DELETE_VARIANT_RESET";
export const DELETE_VARIANT_FAIL = "DELETE_VARIANT_FAIL";

export const SINGLE_VARIANT_REQUEST = "SINGLE_VARIANT_REQUEST";
export const SINGLE_VARIANT_SUCCESS = "SINGLE_VARIANT_SUCCESS";
export const SINGLE_VARIANT_FAIL = "SINGLE_VARIANT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";